name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: rake lint

      - name: Run Minitest
        run: rake test
